### ISSUE TITLE
Don't cast mount if in Ghost Wolf

### ISSUE THREAD

**Issue by BalurPoco** [sfmict/MountsJournal_Classic#1]
Hello,

Currently if I'm in Ghost Wolf and click Summon1/2 it cast a mount.
But instead I just want to cancel the form on the first click.
And cast mount only the second click (when I'm no longer in form).

I would like to request such a setting.

**Comment by sfmict** [comment]
Hello, you can use this macro:
```
/click [noform]MountsJournal_Mount
/cancelform [form]
```

**Comment by sfmict** [comment]
No problem, thx for feedback :)

**Comment by BalurPoco** [comment]
In combat, if I mounted on ground or flying, and press the button I get into ghost wolf, but just want to dismount.
Do you have a fix for this?
Both macros are enabled in settings for easy cast ghost wolf if moving or in combat.

**Comment by sfmict** [comment]
Try this
```
/click [noform,nomounted]MountsJournal_Mount
/dismount [mounted]
/cancelform [form]
```
