### ISSUE TITLE
[Feature Request] Add option for dismount+flight mount cast if on ground mount in flyable area

### ISSUE THREAD

**Issue by Kolmarwow** [sfmict/MountsJournal_Classic#10]
#### Environment
* Addon version: 3.4.27
* WoW version: WotLK Classic 3.4.1 (48340)

#### Current Functionality
If you enter a flyable area on a ground mount and you want to go on a flying mount, then you need to press macro once to dismount and again to get on flying mount.
#### Desired functionality
Add an option that lets you do both dismount+mount flyable mount on 1 macro press if it detects you're on a ground mount in a flyable area.

**Comment by sfmict** [comment]
Hello, it's correct behavior. If you on a mount then you dismount. If I change that then this behavior will be unpredictable action.

**Comment by Kolmarwow** [comment]
i know it's correct behavior, i was asking for option in interface option to change it like this.
