### ISSUE TITLE
[Classic Wrath] Mounts.lua    table index is nil 3.4.3.51666

### ISSUE THREAD

**Issue by jasskin** [sfmict/MountsJournal_Classic#11]
#### Environment
* Addon version: 
* WoW version: 

#### Steps to reproduce
Load WoW Classic Wrath

#### Expected Behaviour
Mounts index in addon
macro summon mounts

#### Actual Behaviour
Addon not loading mounts
macro not mounting character gives error about having a fav mount set.

#### Debug Output

Date: 2023-10-10 17:53:36
ID: 4
Error occured in: Global
Count: 1
Message: Interface/AddOns/MountsJournal/Mounts.lua line 297:
   table index is nil
Debug:
   [string "=[tsm error check]"]:1: in main chunk
   [string "=(tail call)"]: ?
   [string "=[C]"]: ?
   [string "@Interface/AddOns/MountsJournal/Mounts.lua"]:297: updateIndexBySpellID()
   [string "@Interface/AddOns/MountsJournal/Mounts.lua"]:178: ?()
   [string "@Interface/AddOns/MountsJournal/Mounts.lua"]:8:
      Interface/AddOns/MountsJournal/Mounts.lua:8
Locals:

AddOns:
  Swatter, v3.4.6977 (SwimmingSeadragon)
  WowheadLooter, v30403
  342Fix, v3.4.2
  AllTheThings, vDF-3.6.7
  AtlasLootClassic, vv3.1.3
  AtlasLootClassicData, vv3.1.3
  AtlasLootClassicDungeonsAndRaids, vv3.1.3
  AucAdvanced, v3.4.6952 (SwimmingSeadragon)
  AucFilterBasic, v3.4.6941 (SwimmingSeadragon)
  AucStatHistogram, v3.4.6928 (SwimmingSeadragon)
  AucStatiLevel, v3.4.6913 (SwimmingSeadragon)
  AucStatPurchased, v3.4.6910 (SwimmingSeadragon)
  AucStatSimple, v3.4.6911 (SwimmingSeadragon)
  AucStatStdDev, v3.4.6912 (SwimmingSeadragon)
  AucUtilFixAH, v3.4.6914 (SwimmingSeadragon)
  AutoBarWrath, v3.04.1.01
  AutoCombatLogger, v10.1.1
  BagBrother, v
  Bagnon, v10.1.13
  BeanCounter, v3.4.6983 (SwimmingSeadragon)
  BetterFishing, v1.1.18
  BuffomatClassic, v2023.8.1-955e9415
  DBMCore, vd87d92f
  DBMStatusBarTimers, vd87d92f
  DejaClassicStats, v30402r1
  Details, v#Details.20230913.11914.155
  DetailsCompare2, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  ElvUI, v13.42
  ElvUILibraries, v13.42
  Enchantrix, v3.4.6979 (SwimmingSeadragon)
  FojjiCore, v
  Gargul, v6.2.6
  GatherMate2, v1.47.2-classic
  GatherMate2GasClouds, v1.8
  GuildRosterManager, v1.989
  Informant, v3.4.6980 (SwimmingSeadragon)
  ItemRack, v3.75
  LeatrixMaps, v3.0.153.alpha.1
  LeatrixPlus, v3.0.152
  MountsJournal, vv3.4.31
  OmniCC, v10.1.2
  Questie, v8.10.5
  RatingBuster, v
  RCLootCouncilClassic, v0.19.0
  SharedMedia, v3.1.1-199
  SharedMediaMyMedia, v
  SlideBar, v3.4.6919 (SwimmingSeadragon)
  Stubby, v3.4.6920 (SwimmingSeadragon)
  TidyPlatesThreatPlates, v11.1.29
  TomTom, vv3.5.2-release
  TradeSkillMaster, vv4.13.14
  TradeSkillMasterAppHelper, vv4.13
  VuhDo, v3.153-wotlkc
  VuhDoOptions, v3.153-wotlkc
  WeakAuras, v5.8.1
  BlizRuntimeLib v3.4.3.51666(US) <enUS>
  (ck=72b)

**Comment by jasskin** [comment]
Clicking the mount macro give this error


Date: 2023-10-10 18:19:02
ID: 8
Error occured in: Global
Count: 1
Message: Interface/AddOns/MountsJournal/Mounts.lua line 453:
   attempt to index local 'zoneMounts' (a nil value)
Debug:
   [string "=[tsm error check]"]:1: in main chunk
   [string "=(tail call)"]: ?
   [string "=[C]"]: ?
   [string "@Interface/AddOns/MountsJournal/Mounts.lua"]:453: setMountsList()
   [string "@Interface/AddOns/MountsJournal/Mounts.lua"]:562: setFlags()
   [string "@Interface/AddOns/MountsJournal/mixins/MacroMixin.lua"]:375: getMacro()
   [string "@Interface/AddOns/MountsJournal/mixins/MacroMixin.lua"]:456:
      Interface/AddOns/MountsJournal/mixins/MacroMixin.lua:453
   [string "=[C]"]: Click()
   [string "@Interface/FrameXML/ChatFrame.lua"]:1638: ?()
   [string "@Interface/FrameXML/ChatFrame.lua"]:4945: ChatEdit_ParseText()
   [string "@Interface/FrameXML/ChatFrame.lua"]:4628: ChatEdit_SendText()
   [string "@Interface/FrameXML/ChatFrame.lua"]:3007:
      Interface/FrameXML/ChatFrame.lua:3000
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: UseAction()
   [string "@Interface/FrameXML/SecureTemplates.lua"]:343: handler()
   [string "@Interface/FrameXML/SecureTemplates.lua"]:625:
      Interface/FrameXML/SecureTemplates.lua:569
   [string "=[C]"]: ?
   [string "@Interface/FrameXML/SecureHandlers.lua"]:266:
      Interface/FrameXML/SecureHandlers.lua:263
   [string "=[C]"]: ?
   [string "@Interface/FrameXML/SecureHandlers.lua"]:296:
      Interface/FrameXML/SecureHandlers.lua:279
   [string "=(tail call)"]: ?
Locals:

AddOns:
  Swatter, v3.4.6977 (SwimmingSeadragon)
  WowheadLooter, v30403
  342Fix, v3.4.2
  AllTheThings, vDF-3.6.7
  AtlasLootClassic, vv3.1.3
  AtlasLootClassicData, vv3.1.3
  AtlasLootClassicDungeonsAndRaids, vv3.1.3
  AucAdvanced, v3.4.6952 (SwimmingSeadragon)
  AucFilterBasic, v3.4.6941 (SwimmingSeadragon)
  AucScanData, v3.4.6908 (SwimmingSeadragon)
  AucStatHistogram, v3.4.6928 (SwimmingSeadragon)
  AucStatiLevel, v3.4.6913 (SwimmingSeadragon)
  AucStatPurchased, v3.4.6910 (SwimmingSeadragon)
  AucStatSimple, v3.4.6911 (SwimmingSeadragon)
  AucStatStdDev, v3.4.6912 (SwimmingSeadragon)
  AucUtilFixAH, v3.4.6914 (SwimmingSeadragon)
  AutoBarWrath, v3.04.1.01
  AutoCombatLogger, v10.1.1
  BagBrother, v
  Bagnon, v10.1.13
  BagnonConfig, v
  BeanCounter, v3.4.6983 (SwimmingSeadragon)
  BetterFishing, v1.1.18
  BuffomatClassic, v2023.8.1-955e9415
  DBMCore, vd87d92f
  DBMStatusBarTimers, vd87d92f
  DejaClassicStats, v30402r1
  Details, v#Details.20230913.11914.155
  DetailsCompare2, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  ElvUI, v13.42
  ElvUILibraries, v13.42
  ElvUIOptions, v13.42
  Enchantrix, v3.4.6979 (SwimmingSeadragon)
  FojjiCore, v
  Gargul, v6.2.6
  GatherMate2, v1.47.2-classic
  GatherMate2GasClouds, v1.8
  GuildRosterManager, v1.989
  Informant, v3.4.6980 (SwimmingSeadragon)
  ItemRack, v3.75
  LeatrixMaps, v3.0.153.alpha.1
  LeatrixPlus, v3.0.152
  MountsJournal, vv3.4.31
  OmniCC, v10.1.2
  Questie, v8.10.5
  RatingBuster, v
  RCLootCouncilClassic, v0.19.0
  SharedMedia, v3.1.1-199
  SharedMediaMyMedia, v
  SlideBar, v3.4.6919 (SwimmingSeadragon)
  Stubby, v3.4.6920 (SwimmingSeadragon)
  TidyPlatesThreatPlates, v11.1.29
  TomTom, vv3.5.2-release
  TradeSkillMaster, vv4.13.14
  TradeSkillMasterAppHelper, vv4.13
  VuhDo, v3.153-wotlkc
  VuhDoOptions, v3.153-wotlkc
  WeakAuras, v5.8.1
  BlizRuntimeLib v3.4.3.51666(US) <enUS>
  (ck=781)

**Comment by sfmict** [comment]
Not relevant
