### ISSUE TITLE
settings are not stored per character

### ISSUE THREAD

**Issue by kkatee** [sfmict/MountsJournal_Classic#12]
settings are not stored per-character. when you select mounts on one character it affects all characters.

**Comment by sfmict** [comment]
Hello, this never worked by character only by profile

**Comment by kkatee** [comment]
must be time to fix it then

**Comment by sfmict** [comment]
You can create a profile for any character, so no fixing is required.

**Comment by kkatee** [comment]
there is no profile options in the settings window.

**Comment by sfmict** [comment]
The profiles are in the journal on the bottom
