### ISSUE TITLE
No favorite mounts available, can't select any (when indoors)

### ISSUE THREAD

**Issue by b-morgan** [sfmict/MountsJournal_Classic#13]
#### Environment
* Addon version: 3.4.32
* WoW version: 3.4.3

Level 80 character (Warlock), 38 mounts collected. Addon macro says no valid favorite mounts, /mj shows "You can learn riding..."

Have the ability to select favorite mounts.

No mounts shown, No favorite mounts

No debug output

![image](https://github.com/sfmict/MountsJournal_Classic/assets/1547854/9e0aa3cf-39cb-49f3-92ff-c57ad1a95a43)

**Comment by sfmict** [comment]
Hello, u have an unusable filter disabled.

**Comment by sfmict** [comment]
Blizzard brought more from retail, so now the addon can track more environmental changes and etc.

**Comment by Fawa** [comment]
Also want to chime in, you should be able to select flying mounts in ground mount areas (minus Dalaran). Doing so yields, no valid favourite mounts. 

![image](https://github.com/sfmict/MountsJournal_Classic/assets/1351265/d9baf6ea-1b32-475f-88d5-8aab1d07d162)

**Comment by b-morgan** [comment]
IMO, the selection of favorite mounts should be allowed anywhere. Perhaps this is as simple as changing the defaults on the filter. Obviously, when clicking on the macro, "unusable" is enforced.

**Comment by sfmict** [comment]
> Also want to chime in, you should be able to select flying mounts in ground mount areas (minus Dalaran). Doing so yields, no valid favourite mounts.

Thx for feedback, fixed :)
