### ISSUE TITLE
Aspect of cheetah not working with addon

### ISSUE THREAD

**Issue by diabolakos** [sfmict/MountsJournal_Classic#14]
#### Environment
* Addon version: 3.4.33
* WoW version: WotLK 3.4.3.51666

no actual stels. functionality is not working

when indoors or combat and press the macro, hunter does not switch to cheetah but getting error you have no favorite mounts. You cannot do that when moving

#### Actual Behaviour

no lua errors are given

![image](https://github.com/sfmict/MountsJournal_Classic/assets/25266017/e042a21e-fe5a-453f-95ea-383a4563a2f1)

**Comment by sfmict** [comment]
Hello, thx for feedback fixed :)

**Comment by diabolakos** [comment]
its ok now. thank you
