### ISSUE TITLE
Wrath Classic xml templates error

### ISSUE THREAD

**Issue by Road-block** [sfmict/MountsJournal_Classic#15]
#### Environment
* Addon version: 3.4.35
* WoW version: 3.4.3

#### Steps to reproduce
Load the game and show the Collections Interface.

#### Debug Output
```
1x MountsJournal/templates.xml:861 Couldn't find inherited node: MJCalendarPrev
```
```
1x MountsJournal/templates.xml:871 Couldn't find inherited node: MJCalendarNext
```

**Comment by sfmict** [comment]
Helli, thx u for the feedback, fixed :)
