### ISSUE TITLE
Warlocks below level 40 can attempt to summon Dreadsteed but fail

### ISSUE THREAD

**Issue by zeress** [sfmict/MountsJournal_Classic#16]
#### Environment
* Addon version: 4.4.1
* WoW version: 4.4.0 (54525)

#### Steps to reproduce

1. Be a warlock that is level 20-39 and has mount training
2. Make sure "[Dreadsteed](https://www.wowhead.com/cata/spell=23161/dreadsteed)" is part of your currently eligible random selection
3. Do "/click MountsJournal_Mount
4. Note that it will try to Summon Dreadsteed

#### Expected Behaviour
It should not even try to summon Dreadsteed without being level 40+, instead summoning any other viable mount as usual

#### Actual Behaviour
It attempts to Summon Dreadsteed and fails. Repeated attempts will correctly reroll to another mount or may try Dreadsteed again.

I imagine that this is caused by the fact that Summon Dreadsteed is a spell that requires a specific level to use unlike most other mounts. It is likely that the paladin mount is also affected by this issue but I cannot confirm.

**Comment by sfmict** [comment]
Hi, thx you for this information, fixed :)

**Comment by zeress** [comment]
Works now, ty!
