### ISSUE TITLE
Missing rarity filter file (or leftover .toc reference)

### ISSUE THREAD

**Issue by Road-block** [sfmict/MountsJournal_Classic#17]
#### Environment
* Addon version: v4.4.4
* WoW version: 4.4.0 (Cata Classic)

#### Steps to reproduce
Login

#### Debug Output
```
4x MountsJournal/MountsJournal.toc:41 Error loading MountsJournal/components/filter/Rarity.lua
```

**Comment by sfmict** [comment]
Fixed, thx you for the feedback :)
