### ISSUE TITLE
[Cata Classic] Zone specific aquatic mount woes

### ISSUE THREAD

**Issue by Road-block** [sfmict/MountsJournal_Classic#18]
#### Environment
* Addon version: 4.4.7
* WoW version: 4.4.0

#### Steps to reproduce

1. Mark the Abyssal Seahorse as an aquatic mount so it gets used by default in Vash'jir
2. Try to mount while swimming in any water that is _not_ Vash'jir

#### Expected Behavior
Expected maybe not, but desirable yes 😅 
Aquatic mount used in Vash'jir.
Default behavior when swimming or submerged in other zones.

#### Actual Behavior
Seahorse set as an aquatic mount: 
- Correct behavior in Vash'jir, 
- Wrong behavior in other waters (makes it impossible to use Mounts Journal Classic keybinds / macros to mount in water and ride or fly out of it)

Seahorse not set as an aquatic mount:
- Correct behavior in non-Vash'jir waters.
- Wrong behavior in Vash'jir (generic flyable/non-flyable status applies)

#### Debug Output
This is a logic "bug" there are no Lua errors

**Comment by sfmict** [comment]
Abyssal Seahorse is used auto in Vash'jir, I don't play classic, but the same code works fine in retail, and I tested it on a different location and mount, can't reproduce -_-.

**Comment by Road-block** [comment]
That's peculiar.

I got the message about wrong zone after  I set Seahorse as aquatic (only aquatic) at Stormwind Canals.
To be clear Seahorse works great in Vash'jir.

My problem is it tries to use it in other zones when in water where it can't be used.

**Comment by Road-block** [comment]
> Seahorse don't need to be set, it must be auto used in Vash'jir

Oh ty, user error then 😊
