### ISSUE TITLE
References to retail-only LUA files

### ISSUE THREAD

**Issue by Elberet** [sfmict/MountsJournal_Classic#19]
The current version of MountsJournal_Classic - v4.4.17 as per CurseForge - apparently references LUA files which only exist in the retail version of MountsJournal. On starting Cataclysm Classic and entering the world, I get these LUA errors:

```
MountsJournal/components/components.xml:7 Error loading MountsJournal/Help.lua
MountsJournal/components/components.xml:13 Error loading MountsJournal/SummonPanel.lua
MountsJournal/components/filter/filter.xml:11 Error loading MountsJournal/Rarity.lua
```

**Comment by sfmict** [comment]
Thx you for the feedback, fixed :)

**Comment by Elberet** [comment]
Thanks! :+1:
