### ISSUE TITLE
Kalu'ak Whalebone Glider as a ground mount

### ISSUE THREAD

**Issue by BalurPoco** [sfmict/MountsJournal_Classic#2]
Hello,

Kalu'ak Whalebone Glider can be used as a ground mount too, but I cannot summon it by the addon.

**Comment by sfmict** [comment]
Did you select the glider as a ground mount?

**Comment by sfmict** [comment]
Mb you used it in classic locations, so flying mounts can't be used there. If you can use any flying mounts please write about them.

**Comment by BalurPoco** [comment]
I can use the glider as ground mount in Azeroth, Strange, maybe blizzard didn't want it that way, but it works.

**Comment by sfmict** [comment]
Fixed, added some else flying mounts for use in the classic locations.

**Comment by BalurPoco** [comment]
Thanks, its working fine.
