### ISSUE TITLE
[Cata Classic] Magic Broom option not working

### ISSUE THREAD

**Issue by Road-block** [sfmict/MountsJournal_Classic#21]
#### Environment
* Addon version: v4.4.25
* WoW version: 4.4.0

#### Steps to reproduce
Settings > Main > 
```md
[v] Use [Magic Broom]
```

#### Expected Behaviour
Mount the Magic Broom by default when you have the item

#### Actual Behaviour
\*Nothing\*

#### Debug Output
No Lua errors, this is a logic bug.

**Comment by Road-block** [comment]
The problem here is in the macroFrame:getMacro() function.

`self.magicBroom` when all the short-circuit logic passes ends up being an itemName "Magic Broom".
But further down the 
`if self.magicBroom then` conditional tries to use it as an array,
self.magicBroom.itemID and self.magicBroom.mountID do not exist.

```lua
macro = self:getDefMacro()
if self.magicBroom then
	if self.broomID then
		macro = self:addLine(macro, "/use item:"..self.broomID) -- USE ITEM BROOM
	elseif self.broomMountID then
		local name = C_MountJournal.GetMountInfoByID(self.broomMountID)
		macro = self:addLine(macro, "/use "..name) -- USE MOUNT BROOM
	end
	self.lastUseTime = GetTime()
else
        --<snipped>
```
or similar would work

**Comment by sfmict** [comment]
Thx you, fixed :)
