### ISSUE TITLE
Mount macro no longer functional. 11.0.2

### ISSUE THREAD

**Issue by godsyn** [sfmict/MountsJournal_Classic#23]
I assume due to the macro changes in 11.0.2 (https://warcraft.wiki.gg/wiki/Patch_11.0.2/API_changes) the macros no longer work. Is there a /script I could run instead?

**Comment by sfmict** [comment]
Hi, unfortunately no, /script and /run are insecure, you can only bу used with [SecureActionButtonTemplate](https://warcraft.wiki.gg/wiki/SecureActionButtonTemplate)

**Comment by godsyn** [comment]
How frustrating
This means that it can't be on an action bar any more, and triggered by the
action bars's key press. Is this correct?

**Comment by sfmict** [comment]
Yes, that is correct.
