### ISSUE TITLE
Cataclysm Classic Druid Swift Flight form not working

### ISSUE THREAD

**Issue by Rorthron** [sfmict/MountsJournal_Classic#24]
Addon version: 4.4.28
WoW version: Cataclysm Classic latest

I am in deepholm on my 84 druid and what was working fine before when using default settings to enter swift flight form, no longer works. I have a macro with the following 

/click MountsJournal_Mount LeftButton 1

At the moment when I use this macro with these settings. 

![image](https://github.com/user-attachments/assets/e73c50ce-ffac-476a-a466-07caf9064fc4)

Nothing happens. I do not enter swift flight form. Character stays as is.

If I disable everything like this

![image](https://github.com/user-attachments/assets/4874287a-2a2a-45f1-a526-d80413cd413c)

it just mounts my favourite ground mount as expected

Since I can't use swift flight form from the models, I have no way to use this. Is there something else I need to do? Have the spells for flight form changed?

Thanks

**Comment by sfmict** [comment]
Hi, blizz disabled chain macros so `/click` macros don't work anymore, you need to bind a key or use the summon panel.

**Comment by Rorthron** [comment]
This is not the issue. All other characters with different classes use the same macro and it works fine. The druid macro works when these options are disabled as shown. That uses the click option.

**Comment by sfmict** [comment]
Because druids use macro instead of mounts, use the binding key or the summon panel

**Comment by Rorthron** [comment]
OK fair enough. Mapped to keybind instead.

**Comment by Rorthron** [comment]
OK fair enough. Mapped to keybind instead.
