### ISSUE TITLE
Cataclysm Druid - Issue when dismounting when mapped key

### ISSUE THREAD

**Issue by Rorthron** [sfmict/MountsJournal_Classic#25]
Following on from previous issue. I've changed now to use the key bind option with MJ. 

![image](https://github.com/user-attachments/assets/8dc096fe-8dac-46d5-ad51-3b17bb72884e)

So I have Middle Mouse mapped to the default druid class settings. 

![image](https://github.com/user-attachments/assets/9645c534-98ae-4cfd-91fa-bb52b06b41dd)

If I click the Summon Panel 1 to go onto the mount, I enter Swift Flight Form. 

If I click the Summon Panel 1 again, I dismount and go into caster form in druid. All good. This is expected behaviour.

Now, I do the same with my mapped key (middle mouse), when I click I go into Swift Flight Form

If I click the Middle Mouse again, I dismount (first time only).

However, if I click Middle Mouse again and enter Swift Flight form, I am unable to use the mapped key to dismount. I am stuck in flight form. It dismounts very briefly then enters flight form again. 

I think something is wrong with the logic to return to the last form when using the mapped key and it seems to be caching the flight form. With the session panel it works fine every time. 

Here's a quick video of me trying 4 times to dismount using the mapped key. 

https://github.com/user-attachments/assets/a8205dd4-aca5-4135-a5a1-71f023fe9354

**Comment by sfmict** [comment]
Hi, as I understand it, on down is dismounting, and on up is returning the form?)

**Comment by Rorthron** [comment]
This was a click of middle mouse button, not scroll action.

**Comment by sfmict** [comment]
I'm talking about pressing and releasing the button)

**Comment by Rorthron** [comment]
Yes, if I press and hold the druid returns to caster form and falls. When I release, it goes back to flight form.

**Comment by sfmict** [comment]
Fixed, thx you for the feedback :)

**Comment by Rorthron** [comment]
Brilliant - checked and works fine. Thanks
