### ISSUE TITLE
Section of Underbelly Unable to Mount

### ISSUE THREAD

**Issue by kdim953** [sfmict/MountsJournal_Classic#3]
#### Environment
* Addon version: v3.4.17
* WoW version: 3.4.0 (46158)

See attached image - highlighted area is showing as "You can't use that here", but manually mounting a ground mount from the pet tab works fine. Using MoutsJournal Summon 1 with a singular ground and flying mount enabled.

MountsJournal successfully uses a ground mount

Error message "You can't use that here"

N/A

![Untitled](https://user-images.githubusercontent.com/19291898/197079304-f232ef5a-9ee2-4c6e-a5b6-fee3d4e7a24d.png)

**Comment by sfmict** [comment]
Hello, i didn't understand, in this area you can't use flying mounts and you can use ground, and the addon is trying to use flying or what?

**Comment by sfmict** [comment]
Fixed, check pls :)

**Comment by kdim953** [comment]
confirmed working, ty!
