### ISSUE TITLE
Cannot mount in Arenas

### ISSUE THREAD

**Issue by chedster** [sfmict/MountsJournal_Classic#4]
#### Environment
* Addon version: v3.4.19
* WoW version: 3.4.0 (build 46248)

#### Steps to reproduce
1. Attempt to use keybind to mount in an Arena

#### Expected Behaviour
1. Character casts and is successfully mounted

#### Actual Behaviour
1. Addon throws an error and character is left unmounted; No cast is ever performed.

#### Debug Output
```
72x MountsJournal\Mounts-Mounts.lua:482: Usage: local info = C_Map.GetMapInfo(uiMapID)
[string "=[C]"]: in function `GetMapInfo'
[string "@MountsJournal\Mounts-Mounts.lua"]:482: in function `setMountsList'
[string "@MountsJournal\Mounts-Mounts.lua"]:603: in function `setFlags'
[string "@MountsJournal\mixins/MacroMixin.lua"]:375: in function `getMacro'
[string "@MountsJournal\mixins/MacroMixin.lua"]:454: in function <MountsJournal\mixins/MacroMixin.lua:451>

Locals:
(*temporary) = nil
```

#### Screenshots
N/A

**Comment by sfmict** [comment]
Hello, thx for feedback. Fixed, check pls.

**Comment by chedster** [comment]
No longer having the issue, thanks!
