### ISSUE TITLE
Druids may treat Swift Flight Form as a Mount

### ISSUE THREAD

**Issue by boktai1000** [sfmict/MountsJournal_Classic#6]
#### Environment
* Addon version: 3.4.23
* WoW version: 3.4.0.46248

#### Desired functionality

Still having issues with my Druid and the following use case:

- My Flying mount is Swift Flight Form, no other Flying Mount

- I have 100% ground mounts learned and need to be able to use them in various places (Dalaran, Azeroth, BGs, etc)

It seems it's one or the other for me. I've tried a bunch of options in Class Settings > Druid with the "Use this macros instead of mounts" option, as well as Enabling one or both of the Macros but am never to able to get things to quite work as expected.

The closest I can get is when I am moving I can get that one macro to work and cast Swift Flight Form when I am moving, but I'd say that's not exactly ideal in my opinion. I'd like an option for Druids where it works just like regular MountsJournal would on other classes, except I can treat my Swift Flight Form (or Flight Form in general) as a mount according to MountsJournal and cast it appropriately when possible.

Really I cannot thank you enough for this Addon. It's just part of Wrath Classic for me now, it feels like what we should have in the game. As I'm getting more time to go through different Alts of mine now in Wrath, this issue is becoming a bit more problematic so I wanted to throw something out there. Please let me know if there's more information you need from me here!

(Note: Comment posted to Curseforge as well, decided it may be better to open Feature Request here instead/as well for your own tracking purposes - https://www.curseforge.com/wow/addons/mountsjournal_classic?comment=47 )

**Comment by sfmict** [comment]
hello, added an option, check :)
