### ISSUE TITLE
Mounts not showing up

### ISSUE THREAD

**Issue by slapaglia** [sfmict/MountsJournal_Classic#7]
After updating the addon, the mounts no longer show up.  The macro still seems to summon mounts properly but it doesn't recognize you have mounts.  Screen shows information on getting mounts at level 20.  Have tried to uninstall and reinstall via CurseForge app.  No resolution.

**Comment by sfmict** [comment]
Hello, the latest version is for game version 3.4.1

**Comment by Bap455** [comment]
That doesn't change the fast this great addon is broke atm, can it be fixed so mounts show in the current game please :)

**Comment by fubar-coder** [comment]
The "solution" currently is to downgrade to version 3.4.25.

**Comment by Bap455** [comment]
Ok thank you, love the addon :)

**Comment by sfmict** [comment]
Did wow update? or not i don't have the wotlk client.

**Comment by fubar-coder** [comment]
The WoW WOTLK client is still on version 3.4.0.46902

**Comment by sfmict** [comment]
So the latest release is temporarily removed.
