### ISSUE TITLE
Bug Sack - Addon Error

### ISSUE THREAD

**Issue by WorkPixels** [sfmict/MountsJournal_Classic#8]
9x ...rface\AddOns\MountsJournal\mixins/CompanionMixin.lua:64: attempt to index field 'petForMount' (a nil value)
[string "@Interface\AddOns\MountsJournal\mixins/CompanionMixin.lua"]:64: in function `refresh'
[string "@Interface\AddOns\MountsJournal\mixins/CompanionMixin.lua"]:46: in function <...rface\AddOns\MountsJournal\mixins/CompanionMixin.lua:44>

Locals:
self = <unnamed> {
 0 = <userdata>
 journal = MountsJournalFrame {
 }
 onShow = <function> defined @Interface\AddOns\MountsJournal\mixins/CompanionMixin.lua:42
 onLoad = <function> defined @Interface\AddOns\MountsJournal\mixins/CompanionMixin.lua:9
 infoFrame = <unnamed> {
 }
 refresh = <function> defined @Interface\AddOns\MountsJournal\mixins/CompanionMixin.lua:62
 event = <function> defined @Interface\AddOns\MountsJournal\Util.lua:50
 onEvent = <function> defined @Interface\AddOns\MountsJournal\mixins/CompanionMixin.lua:39
 mounts = MountsJournal {
 }
 off = <function> defined @Interface\AddOns\MountsJournal\Util.lua:22
 highlight = <unnamed> {
 }
 arrow = <unnamed> {
 }
 border = <unnamed> {
 }
 bg = <unnamed> {
 }
 onClick = <function> defined @Interface\AddOns\MountsJournal\mixins/CompanionMixin.lua:53
 on = <function> defined @Interface\AddOns\MountsJournal\Util.lua:6
}
spellID = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'petForMount' (a nil value)"
petRandomIcon = "MountsJournal/textures/INV_Pet_Achievement_CaptureAPetFromEachFamily_Battle"

**Comment by sfmict** [comment]
What is version of the addon, wow version, how to reproduce it? I need more information.

**Comment by WorkPixels** [comment]
I'm not sure I'm tried deleting save variables and re-installing. I keep getting the same error. When I look in Bug Sack I get those strings of errors.

WoW Classic WotLK
MountsJournal-v3.4.26.zip

9x Interface\AddOns\MountsJournal\Journal.lua:2505: attempt to index field 'petForMount' (a nil value)
[string "@Interface\AddOns\MountsJournal\Journal.lua"]:2505: in function `updateMountsList'
[string "@Interface\AddOns\MountsJournal\Journal.lua"]:97: in function <Interface\AddOns\MountsJournal\Journal.lua:87>
[string "=[C]"]: in function `SetShown'
[string "@Interface\AddOns\MountsJournal\Journal.lua"]:2552: in function `showToggle'
[string "@Interface\AddOns\MountsJournal\Mounts-Mounts.lua"]:102: in function `OnClick'
[string "@Interface\AddOns\Bartender4\libs\LibDBIcon-1.0\LibDBIcon-1.0-45.lua"]:144: in function <...dOns\Bartender4\libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:142>

Locals:
self = MountsJournalFrame {
 0 = <userdata>
 yMinSpeed = <unnamed> {
 }
 xMinSpeed = <unnamed> {
 }
 clearBtnFilters = <function> defined @Interface\AddOns\MountsJournal\Journal.lua:2313
 setScrollGridMounts = <function> defined @Interface\AddOns\MountsJournal\Journal.lua:934
 selectMount = <function> defined @Interface\AddOns\MountsJournal\Journal.lua:1722
 filtersBar = <unnamed> {
 }
 mountToggle = <function> defined @Interface\AddOns\MountsJournal\Journal.lua:1378
 updateMountDisplay = <function> defined @Interface\AddOns\MountsJournal\Journal.lua:1598
 setAllFilters = <function> defined @Interface\AddOns\MountsJournal\Journal.lua:2305
 PLAYER_REGEN_DISABLED = <function> defined @Interface\AddOns\MountsJournal\Journal.lua:906
 createMountList = <function> defined @Interface\AddOns\MountsJournal\Journal.lua:1346
 updateMapSettings = <function> defined @Interface\AddOns\MountsJournal\Journal.lua:1518
 updateBtnFilters = <function> defined @Interface\AddOns\MountsJournal\Journal.lua:2387
 mountDisplay = <unnamed> {
 }
 yAcceleration = <unnamed> {
 }
 displayedMounts = <table> {
 }
 setShownCountMounts = <function> defined @Interface\AddOns\MountsJournal\Journal.lua:2480
 setFlag = <function> defined @Interface\AddOns\MountsJournal\Journal.lua:1400
 default_UpdateMountList = <function> defined @Interface\AddOns\MountsJournal\Journal.lua:333
 defaultUpdateMountList = <function> defined @Interface\AddOns\MountsJournal\Journal.lua:989
 bgFrame = MountsJournalBackground {
 }
 tags = <table> {
 }
 saveDefaultFilters = <function> defined @Interface\AddOns\MountsJournal\Journal.lua:2202
 grid3UpdateMountList = <function> defined @Interface\AddOns\MountsJournal\Journal.lua:1091
 on = <function> defined @Interface\AddOns\MountsJournal\Util.lua:6
 isMountHidden = <function> defined @Interface\AddOns\MountsJournal\Journal.lua:2458
 shownPanel = <unnamed> {
 }
 sortMounts = <function> defined @Interface\AddOns\MountsJournal\Journal.lua:1277
 mapSettings = <unnamed> {
 }
 PLAYER_ENTERING_WORLD = <function> defined @Interface\AddOns\MountsJournal\Journal.lua:1337
 updateCountMounts = <function> defined @Interface\AddOns\MountsJournal\Journal.lua:1271
 summonButton = <unnamed> {
 }
 existingLists = <unnamed> {
 }
 getFilterWeight = <function> defined @Interface\AddOns\MountsJournal\Journal.lua:2463
 gridToggleButton = <unnamed> {
 }
 filtersButton = <unnamed> {
 }
 mountCount = <unnamed> {
 }
 event = <function> defined @Interface\AddOns\MountsJournal\Util.lua:50
 updateMountsList = <function> defined @Interface\AddOns\MountsJournal\Journal.lua:2493
 off = <function> defined @Interface\AddOns\MountsJournal\Util.lua:22
 filtersToggle = <unnamed> {
 }
 xAcceleration = <unnamed> {
 }
 getRemoveMountList = <function> defined @Interface\AddOns\MountsJournal\Journal.lua:1357
 grid3_UpdateMountList = <function> defined @Interface\AddOns\MountsJournal\Journal.lua:334
 restoreDefaultFilters = <function> defined @Interface\AddOns\MountsJournal\Journal.lua:2239
 weightFrame = <unnamed> {
 }
 setBtnFilters = <function> defined @Interface\AddOns\MountsJournal\Journal.lua:2366
 leftInset = <unnamed> {
 }
 filtersPanel = <unnamed> {
 }
 ZONE_CHANGED = <function> defined @Interface\AddOns\MountsJournal\Journal.lua:1337
 modelScene = <unnamed> {
 }
 showToggle = <function> defined @Interface\AddOns\MountsJournal\Journal.lua:2548
 useMount = <function> defined @Interface\AddOns\MountsJournal\Journal.lua:1660
 navBarBtn = <unnamed> {
 }
 searchBox = <unnamed> {
 }
 PLAYER_REGEN_ENABLED = <function> defined @Interface\AddOns\MountsJournal\Journal.lua:914
 filterDropDown_Initialize = <function> defined @Interface\AddOns\MountsJournal\Journal.lua:1728
 setSelectedMount = <function> defined @Interface\AddOns\MountsJournal\Journal.lua:1694
 isDefaultFilters = <function> defined @Interface\AddOns\MountsJournal\Journal.lua:2263
 scrollFrame = <unnamed> {
 }
 resetToDefaultFilters = <function> defined @Interface\AddOns\MountsJournal\Journal.lua:2323
 navBar = <unnamed> {
 }
 listFromMapClick = <function> defined @Interface\AddOns\MountsJournal\Journal.lua:1423

**Comment by sfmict** [comment]
What is wow version? Mb you need to switch the addon version to 3.4.25

**Comment by WorkPixels** [comment]
WoW version 3.4.46902

Maybe? I'll try to revert and see if that helps.

**Comment by WorkPixels** [comment]
MountsJournal-v3.4.25 seems to not error out so far.

**Comment by fubar-coder** [comment]
Might be related to #7?

**Comment by sfmict** [comment]
So the latest release is temporarily removed.

**Comment by Zedseayou** [comment]
I am getting this same error (attempt to index field petformount) with the same wow versions (3.4.0.46902) and mountsjournal versions (3.4.25). These are the errors I get:

> Message: Interface\AddOns\MountsJournal\Journal.lua:800: bad argument #2 to 'SetRotation' (number expected, got table)

> Message: ...rface\AddOns\MountsJournal\mixins/CompanionMixin.lua:64: attempt to index field 'petForMount' (a nil value)

> Message: Interface\AddOns\MountsJournal\components\Tags.lua:83: attempt to index field 'mountOptionsMenu' (a nil value)

This happens any time I try to open the main mounts page (e.g. with /mj), and no mounts show up on that page (so I cannot change the selected mounts). The mount macro still works though.
