### ISSUE TITLE
Update generated macros to fallback to ground mount in Dalaran.

### ISSUE THREAD

**Issue by rudiad** [sfmict/MountsJournal_Classic#9]
#### Environment
* Addon version: 3.4.27
* WoW version: 3.4.1

Not sure if you can't do this because you are running up against character limits in your generated macros.

It would be great if your macros could handle falling back to a default ground mount for the Dalaran use case.
```
/castrandom [flyable, nomounted]  Black Proto-Drake
/castrandom [nomounted] Swift White Hawkstrider
```
This allows a single key press to mount up in any situation (obviously not accounting for the larger complexities you are checking for when building your macros.

**Comment by sfmict** [comment]
Hello, I can't change the conditions for the default blizz commands, if that's what you mean.
This addon checks for this already in its macros.

**Comment by rudiad** [comment]
I think its not about checking conditions, because Dalaran has broken conditions. It's about having a redundant non-flying fallback as the last line of any generated macro in order to correct for the incorrect conditions in Dalarn. But its no big deal was just curious.

**Comment by sfmict** [comment]
I didn't fully understand what do you want from me?
The code of these conditions is scattered across different functions, so even if collected, it is unlikely to fit in 255 characters.

**Comment by rudiad** [comment]
Its all good. I can just close this enhancement request. I was hoping to get one of your macros that correctly works in Dalaran instead of needing to use two separate ones.
